### ISSUE TITLE
RFP: Submit a proposal for a descifoundation.org redesign 

### ISSUE THREAD

**Issue by Plikt** [desci-labs/rfps-and-microgrants#4]
We hope to update [our website](https://descifoundation.org/) so that it effectively communicates our mission as nodes and connects people seamlessly to the entire DeSci ecosystem. The current design falls short of achieving these goals, and we are seeking a complete overhaul to address these shortcomings. The redesigned website will prioritize clear and impactful messaging, enhancing the user experience and visual presentation. Through this redesign, our objective is to enhance user engagement, improve information dissemination, and strengthen our connection with the community we serve.

The core of this RFP is simply to submit a redesign proposal that includes your previous experience and expertise. 

**OUTPUT:** A redesigned website.

**Comment by bayraqi** [comment]
Hi,

Would be interested in submitting a proposal for the redesign.

**Comment by jring-o** [comment]
Hello @bayraqi!

Do you have any previous work you'd like to share?
What's your general thinking around the current site and what needs to be improved?

**Comment by Plikt** [comment]
We've finished this RFP - closing it now!
